#!/bin/sh
# set -e
# set -x

# root of work files
WORKPATH={{WORKPATH}}
# live location
LIVEPATH={{LIVEPATH}}
# stage location
STAGEPATH=${WORKPATH}/stage
# git checkout location
GIT_WORK_TREE=${STAGEPATH}

export GIT_WORK_TREE
export LIVEPATH
export STAGEPATH

echo "starting update..."

# cleanup prev checkout
rm -rf ${GIT_WORK_TREE}
mkdir -p ${GIT_WORK_TREE}

# checkout
git checkout -f

# run any user scripts included in repo
echo "running deploy scripts..."
for each in ${STAGEPATH}/deploy/scripts/*.sh;
do
    bash $each;
done;

# swap new stage app with live app
# ** TODO - possibly update the symlink instead? Quicker, safer?
mv ${LIVEPATH} ${LIVEPATH}.bak
mv ${GIT_WORK_TREE} ${LIVEPATH}
# remove old live app
sudo rm -rf ${LIVEPATH}.bak

echo "** update complete **"